name: GitHub actions
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get install libclang1-9 libclang-cpp9 -y
    - name: Install Doxygen
      run: |
        wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
        tar xzf doxygen-1.9.2.linux.bin.tar.gz
        cd doxygen-1.9.2
        sudo make install
        cd ../
    - name: cmake build
      run: |
        cmake -B build  .
        cmake --build build/doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/out/html